---
title: "Data Processing Code"
author: "Ryan Godin, Saman Ghazvini, William Amendola Bye, Jordyn Eovito, Vencke Gruening"
date: "`r Sys.Date()`"
output: pdf_document
---

The following code prepares the raw data from [Chen et al., 2023's](https://doi.org/10.1021/acssynbio.2c00662) *Deep Mutational Scanning of an Oxygen-Independent Fluorescent Protein CreiLOV for Comprehensive Profiling of Mutational and Epistatic Effects* for the analyses used to reproduce the figures. The raw single point mutation code is given in `data/raw/sb2c00662_si_001.xlsx` while the raw combinatorial mutation data is given in `data/raw/sb2c00662_si_002.xlsx`. The processed data is stored in the `data/processed` folder so that it can be loaded for analyses.

The following libraries are needed for the data processing.

```{R}
rm(list = ls())
library(tidyr)
library(tidyverse)
library(readxl)
library(pbapply)
library(openxlsx)
library(scales)
```

## Single Mutation Data Processing

For the downstream analyses, the following data needs to be extracted from the entries and added as columns to the dataframe:

1. Mutation position
2. Wild-type amino acid
3. Mutant amino acid

### Load the dataset and inspect the file.

```{R}
single_mutant_data <- read_excel("data/raw/sb2c00662_si_001.xlsx")
colnames(single_mutant_data)[1] <- "mutants"
```

Checking the first few lines, last few lines, and dimensions of the file to see if it loaded correctly.

```{R}
head(single_mutant_data)
tail(single_mutant_data)
dim(single_mutant_data)
```

### Extract the mutant amino acid position

```{R}
single_mutant_data <-
  mutate(
    single_mutant_data,
    position = as.integer(str_extract(mutants, "\\d+")),
)
head(single_mutant_data[,c("mutants", "position")])
```

### Extract the wild-type amino acid

The amino acid will be extracted as a one letter code to make the replication of the figures easier. First, we define the table neccessary to convert the three letter to one letter amino acid abbreviation.

```{R}
conversion_table <- c(
    Ala = "A", Arg = "R", Asn = "N", Asp = "D", Cys = "C", 
    Gln = "Q", Glu = "E", Gly = "G", His = "H", Ile = "I", 
    Leu = "L", Lys = "K", Met = "M", Phe = "F", Pro = "P", 
    Ser = "S", Thr = "T", Trp = "W", Tyr = "Y", Val = "V"
)
```

We now extract the one letter amino acid abbreviation for the wild-type amino acid.

```{R}
extract_wt_amino_acid <- function(mutant) {
    mutant <- as.character(mutant)
    if (mutant == "wt") {
        return(NA)
    } else {
        removed_prefix <- str_remove(mutant, "^p\\.")  # Remove "p." prefix
        wt_amino_acid_3_letter <- str_extract(removed_prefix, "^[A-Za-z]+")
        wt_amino_acid_1_letter <- conversion_table[wt_amino_acid_3_letter]
        return(wt_amino_acid_1_letter)
    }
}

single_mutant_data <- mutate(
    single_mutant_data,
    wt_amino_acid = sapply(mutants, extract_wt_amino_acid)
)

head(single_mutant_data[,c("mutants", "position", "wt_amino_acid")])
```

### Extract the mutant amino acid

**NOTE:** You need to load the conversion table from extracting the wild-type amino acid by running the corresponding code block!

```{R}
extract_mutant_amino_acid <- function(mutant) {
    mutant <- as.character(mutant)
    if (mutant == "wt") {
        return(NA)
    } else {
        removed_prefix <- str_remove(mutant, "^p\\.")  # Remove "p." prefix
        wt_amino_acid_3_letter <- str_extract(removed_prefix,  "[A-Za-z]+$")
        wt_amino_acid_1_letter <- conversion_table[wt_amino_acid_3_letter]
        return(wt_amino_acid_1_letter)
    }
}

single_mutant_data <- mutate(
    single_mutant_data,
    mutant_amino_acid = sapply(mutants, extract_mutant_amino_acid)
)

head(single_mutant_data[,c("mutants", "position", "wt_amino_acid", "mutant_amino_acid")])
```

### Save processed data

The processed single mutant data will be exported to `data/processed/single_mutant_data.csv` so that the single mutant data analysis can be run independently of the data processing.

```{R}
write.csv(single_mutant_data, file = "data/processed/single_mutant_data.csv", row.names=FALSE)
```

## Double Mutation Data Processing

To process the raw combinatorial mutation data, the following data needs to be extracted/calculated from the raw mutation data.

1. The position of the mutation.
2. Number of mutations.
3. Expected fluorescence based on summing the effects of the individual mutations.
4. Level of Epistasis.

We first load the raw combinatorial mutation datast.

```{R}
combinatorial_mutation_data <- read_excel("data/raw/sb2c00662_si_002.xlsx")
colnames(combinatorial_mutation_data)[1] <- "mutants"
```

Checking the first few lines, last few lines, and dimensions of the file to see if it loaded correctly.

```{R}
head(combinatorial_mutation_data)
tail(combinatorial_mutation_data)
dim(combinatorial_mutation_data)
```


### Extract position

We now extract the position for the mutants by extracting them from the first column. Note that for mutants with more than one mutation, it extracts just the last mutation position.

```{R}
combinatorial_mutation_data$position <- as.integer(gsub(".*[a-zA-Z](\\d+)[a-zA-Z]*", "\\1", combinatorial_mutation_data[[1]]))
head(combinatorial_mutation_data[,c("mutants", "position")])
tail(combinatorial_mutation_data[,c("mutants", "position")])
```

### Extract the number of mutations

The number of mutations is extracted by calculating then number of entries in the mutants column.

```{R}
count_mutations <- function(mutation_list) {
    mutation_list <- as.character(mutation_list)
    if (mutation_list == "wt") {
        return(0)
    } else {
        mutations_vector <- trimws(strsplit(mutation_list, ",")[[1]])
        return(length(mutations_vector))
    }
}

combinatorial_mutation_data <- mutate(
    combinatorial_mutation_data, mutation_count = sapply(mutants,count_mutations)
)

head(combinatorial_mutation_data[,c("mutants","mutation_count")])
tail(combinatorial_mutation_data[,c("mutants","mutation_count")])
```

### Calculate expected fluorescence

To calculate the expected fluorescence for the combinatorial mutants, we extract the mean log fluorescence for the single mutants and use the following formula provided in the paper where $F_{\mathrm{com}}$, $F_{\mathrm{sin}}$, and $F_{\mathrm{wt}}$ are the log-fluorescence values of combinatorial mutant, single mutant, and WT CreiLOV, respectively.
$$e=\left(F_{\mathrm{com}}-F_{\mathrm{wt}}\right)-\Sigma\left(F_{\mathrm{sin}}-F_{\mathrm{wt}}\right)$$

**Note:** This calculation takes some time for the 160,000 mutants. To speed up this calculation, we extract the single mutant data first and store them so that the program doesn't have to search through 160,000 entries when extracting the single mutants. This sped up runtime from 20 min to 1 min. However, we still include a progress bar for the calculation using `papply` so that progress can be tracked.

```{R}
extracted_single_mutants <- filter(combinatorial_mutation_data, mutation_count < 2)
dim(extracted_single_mutants)

get_single_fluorescence <- function(mutation, mutation_data){
    single_mutation_row <- which(mutation_data[[1]] == mutation)
    return(mutation_data[single_mutation_row,"mean_log"])
}

get_expected_fluorescence <- function(mutation_list, mutation_data){
    mutation_list <- as.character(mutation_list)
    mutations_vector <- trimws(strsplit(mutation_list, ",")[[1]])
    single_mutant_fluorescence <- sapply(mutations_vector, get_single_fluorescence, mutation_data = mutation_data)
    wild_type_fluorescence <- mutation_data[1,"mean_log"]
    expected_fluorescence <- sum(single_mutant_fluorescence[[1]] - wild_type_fluorescence) + wild_type_fluorescence
    return(expected_fluorescence[[1]])
}

combinatorial_mutation_data <- mutate(
    combinatorial_mutation_data, expected_fluorescence = pbapply::pbsapply(mutants,get_expected_fluorescence, mutation_data = extracted_single_mutants)
)

head(combinatorial_mutation_data[,c("mutants","mean_log", "expected_fluorescence")])
tail(combinatorial_mutation_data[,c("mutants","mean_log", "expected_fluorescence")])
```

### Calculate epistasis

We now calculate the level of epistasis (difference betweene expected and observed fluorescence).

```{R}
combinatorial_mutation_data <- mutate(
    combinatorial_mutation_data, epistasis = mean_log - expected_fluorescence
)

head(combinatorial_mutation_data[,c("mutants","mean_log", "expected_fluorescence", "epistasis")])
tail(combinatorial_mutation_data[,c("mutants","mean_log", "expected_fluorescence", "epistasis")])
```

### Save processed data

Like the processed single mutant data, the processed combinatorial mutation data will be exported to `data/processed/combinatorial_mutant_data.csv` so that the data analysis can be run independently of the data processing.

```{R}
write.csv(combinatorial_mutation_data, file = "data/processed/combinatorial_mutant_data.csv", row.names=FALSE)
```

## Analyze Data

Now that the raw data has been processed, the data analysis (figure generation) can now be performed using the designated RMD file: `data_analysis.RMD`.