---
title: "Data Analysis Code"
author: "Ryan Godin, Saman Ghazvini, William Amendola Bye, Jordyn Eovito, Vencke Gruening"
date: "`r Sys.Date()`"
output: pdf_document
---

This code tries to reproduce a select portion of figures from [Chen et al., 2023's](https://doi.org/10.1021/acssynbio.2c00662) *Deep Mutational Scanning of an Oxygen-Independent Fluorescent Protein CreiLOV for Comprehensive Profiling of Mutational and Epistatic Effects*. To run this code, please ensure that the raw data from the paper has been processed and saved in `data/processed` by running the code in `data_processing.RMD`.

The following libraries are needed for the data processing.

```{R}
#rm(list = ls())
library(tidyr)
library(tidyverse)
library(ggbeeswarm)
library(ggplot2)
library(ggpmisc)
library(scales)
```

## Figure Reproduction

### Load the data

```{R}
single_mutant_data <- read.csv("data/processed/single_mutant_data.csv")
combinatorial_mutation_data <- read.csv("data/processed/combinatorial_mutant_data.csv")
```

Checking the first few lines, last few lines, and dimensions of the file to see if the data loaded correctly.

```{R}
head(single_mutant_data)
tail(single_mutant_data)
dim(single_mutant_data)

head(combinatorial_mutation_data)
tail(combinatorial_mutation_data)
dim(combinatorial_mutation_data)
```

### Reproducing Figure 1B

We first calculate the $R$ correlation coefficient and the regression equation so we can annotate the ggplots with them.

```{R}
# Calculate regression data and make labels for plots
regression_12 <- lm(single_mutant_data$rep1 ~ single_mutant_data$rep2)
slope_12 <- coef(regression_12)[2]
r_12 <- cor(single_mutant_data$rep1, single_mutant_data$rep2, use = "complete.obs")
r_label_12 <- paste("italic(R) == ", format(round(r_12, 3), nsmall = 3))
eq_12 <- paste("y == ", round(slope_12, 3), " * x", sep = "")

regression_13 <- lm(single_mutant_data$rep1 ~ single_mutant_data$rep3)
slope_13 <- coef(regression_13)[2]
r_13 <- cor(single_mutant_data$rep1, single_mutant_data$rep3, use = "complete.obs")
r_label_13 <- paste("italic(R) == ", format(round(r_13, 3), nsmall = 3))
eq_13 <- paste("y == ", round(slope_13, 3), " * x", sep = "")

regression_23 <- lm(single_mutant_data$rep3 ~ single_mutant_data$rep2)
slope_23 <- coef(regression_23)[2]
r_23 <- cor(single_mutant_data$rep2, single_mutant_data$rep3, use = "complete.obs")
r_label_23 <- paste("italic(R) == ", format(round(r_23, 3), nsmall = 3))
eq_23 <- paste("y == ", round(slope_23, 3), " * x", sep = "")
```

We next generate the annotated figures and save the subplots to `figures/fig_1b`.

```{R}
fig_1b_1 <- ggplot(single_mutant_data, aes(x = rep1, y = rep2)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
  annotate(
    "text",
    x = min(single_mutant_data$rep1),
    y = max(single_mutant_data$rep2),
    label = eq_12,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  annotate(
    "text",
    x = min(single_mutant_data$rep1),
    y = max(single_mutant_data$rep2) - 2000,
    label = r_label_12,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  labs(title = "Regression Plot for Replicate 1 vs Replicate 2", x = "Replicate 1", y = "Replicate 2")

fig_1b_2 <- ggplot(single_mutant_data, aes(x = rep1, y = rep3)) +
  geom_point() +
  geom_smooth(method = "lm", col = "green") +
  annotate(
    "text",
    x = min(single_mutant_data$rep1),
    y = max(single_mutant_data$rep3),
    label = eq_13,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  annotate(
    "text",
    x = min(single_mutant_data$rep1),
    y = max(single_mutant_data$rep3) - 2000,
    label = r_label_13,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  labs(title = "Regression Plot for Replicate 1 vs Replicate 3", x = "Replicate 1", y = "Replicate 3")

fig_1b_3 <- ggplot(single_mutant_data, aes(x = rep2, y = rep3)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  annotate(
    "text",
    x = min(single_mutant_data$rep2),
    y = max(single_mutant_data$rep3),
    label = eq_23,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  annotate(
    "text",
    x = min(single_mutant_data$rep2),
    y = max(single_mutant_data$rep3) - 2000,
    label = r_label_23,
    parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  labs(title = "Regression Plot for Replicate 2 vs Replicate 3", x = "Replicate 2", y = "Replicate 3")


# Print and save the plots and associated data.
ggsave("figures/fig_1b/fig_1b_1.png", plot = fig_1b_1)
print(fig_1b_1)

ggsave("figures/fig_1b/fig_1b_2.png", plot = fig_1b_2)
print(fig_1b_2)

ggsave("figures/fig_1b/fig_1b_3.png", plot = fig_1b_3)
print(fig_1b_3)
```

### Reproducing Figure 2A

We first load the target wild-type value so that it can be highlighted in the histogram.

```{R}
target_value <- single_mutant_data[1,"log_mean"]
print(target_value)
```

We next generate and format the histogram.

```{R}
## Plot and format the histogram to see if it looks like the paper.
fig_2a <- ggplot(single_mutant_data, aes(x = log_mean, y = after_stat(ndensity))) +
  geom_histogram(
    aes(fill = after_stat(xmin) <= target_value &
          after_stat(xmax) > target_value),
    bins = 47,
    color = "black"
  ) +
  scale_fill_manual(values = c("TRUE" = "red", "FALSE" = "black"),
                    guide = "none") +
  labs(x = "Fluorescence (log)", y = "Frequency") +
  scale_x_continuous(
    limits = c(2, 5),
    breaks = seq(2, 5, by = 0.5),
    labels = sprintf("%.2f", seq(2, 5, by = 0.5)),
    expand = c(0, 0)
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 14, color = "black"),
    axis.title = element_text(size = 16, color = "black"),
    axis.ticks = element_line(color = "black", size = 0.8),
    axis.ticks.length = unit(0.3, "cm"),
    axis.line = element_line(color = "black", size = 0.8)
  )

ggsave("figures/fig_2a.png", plot = fig_2a)
print(fig_2a)
```

### Reproducing Figure 2B

We first extract the necessary data and format it for the heatmap.

```{R}
# Restrict positions to 1-120 and drops those with invalid amino acids.
df_parsed <- filter(
  single_mutant_data,
  position >= 1,
  position <= 120,
  !is.na(wt_amino_acid),
  !is.na(mutant_amino_acid)
)

# Custom amino acid order for Y-axis
aa_order <- c(
  'P',
  'G',
  'F',
  'W',
  'Y',
  'A',
  'I',
  'L',
  'V',
  'C',
  'M',
  'N',
  'Q',
  'S',
  'T',
  'H',
  'K',
  'R',
  'D',
  'E'
)

df_parsed <- df_parsed %>%
  mutate(mutant_amino_acid = factor(mutant_amino_acid, levels = aa_order)
)
```

We then plot the heatmap.

```{R}
# Plot heatmap with all desired features
fig_2b_heatmap <-  ggplot(df_parsed, aes(x = position, y = mutant_amino_acid, fill = mean)) +
  geom_tile(color = "black", linewidth = 0.3) +  # Black borders for tiles
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 14803,
    na.value = "gray80",
    # Lighter gray for missing values
    name = "Fluorescence"
  ) +
  theme_minimal() +
  coord_fixed() +  # Makes tiles square
  theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1,
      size = 7
    ),
    axis.text.y = element_text(size = 4, face = "bold"),
    legend.position = "right",
    legend.key.height = unit(0.5, "cm")  # Taller legend for better color gradient
  ) +
  labs(x = "Position", y = "Mutant Amino Acid", title = "Fluorescence Heatmap")

ggsave("figures/fig_2b_heatmap.png", plot = fig_2b_heatmap,width = 10, height = 6)
print(fig_2b_heatmap)
```

We next generate the figure for the second part of Figure 2B.

```{R}
fig_2b_lower <- ggplot(single_mutant_data, mapping = aes(x = as.factor(position), y = mean)) + 
  geom_boxplot(fill = "black", outlier.shape = NA) + scale_x_discrete(breaks = seq(10, 110, by = 10)) + 
  xlab("Position in CreiLOV Protein") + ylab("Fluorescence") + scale_y_log10(
    breaks = c(1e3, 1e4),
    labels = scales::trans_format("log10", math_format(10^.x))
  ) + 
  theme_classic()

ggsave("figures/fig_2b_lower.png", fig_2b_lower, width = 16, height = 2)
```

### Reproducing Figure 3A

We first set up vector for specified positions as detailed in paper and then select the mutants they singled out and highlighted red in their figure (found in Table S2). 

*Note:* Missing Val107Met - there's no Val107Met data from the s1 single mutant set)

```{R} 
table_s1 <- single_mutant_data
table_s2 <- combinatorial_mutation_data

target_positions <- c(3,4,5,7,29,34,47,60,61,92,96,98,107,109,113)
# Filters selected mutations in combinatorial mutagenesis, found in table S2
selected_mutants <- unlist(c(table_s2[2:21,1]))
# Filters table for selected positions - chosen at various distances
# from FMN chromophore, with high tolerance for amino acid substitutions
# - little detail in paper
filtered_table_s1 <- table_s1[(table_s1$position %in% target_positions), ]
filtered_table_s1_graph <- filter(
  filtered_table_s1, 
  !(filtered_table_s1[[1]] %in% selected_mutants)
)
filtered_table_s2 <- table_s2[2:21, ]
selected_fluorescence <- table_s1[table_s1[[1]] %in% selected_mutants, ]
# Mean wildtype fluorescence extracted to overlay on graph as horizontal line
wt_mean <- as.numeric(c(table_s1[1,5]))
```

We now graph the data to reproduce Figure 3A. To graph fluorescence at each position, we use geom_jitter since it shows points at each position without overlapping. Note that the Horizontal dashed line indicates the wildtype mean fluorescence value.

```{R}
fig_3a <- ggplot(filtered_table_s1_graph, aes(x=factor(position), y=mean)) +
  geom_boxplot(alpha = 0, outlier.shape = NA, coef = 0) +
  geom_jitter() +
  geom_hline(yintercept = wt_mean, linetype = "dashed", color = "blue") +
  geom_point(selected_fluorescence, 
    mapping = aes(x = factor(position), y = mean), color = "red"
  ) +
  scale_y_continuous(
    limits = c(0,3e4), 
    breaks = c(0, 1e4, 2e4, 3e4), 
    labels = c("0", "1E4", "2E4", "3E4")
  ) +
  labs(x = "Positions in CreiLOV Protein", y = "Fluorescence")

ggsave("figures/fig_3a.png", fig_3a, width = 7, height = 2)
print(fig_3a)
```

### Reproducing Figure 3B

The authors combined the replicates for the fluorescence measurement when genrating Figure 3B, so we must first process the data using pivot longer before we can reproduce the figure.

```{R}
combinatorial_mutation_data_long <- pivot_longer(
    combinatorial_mutation_data, cols = c("Rep1", "Rep2", "Rep3"),  
    names_to = "replicate",
    values_to = "value"
)

head(combinatorial_mutation_data_long)
dim(combinatorial_mutation_data_long)
```

We are now ready to generate the figure.

```{R}
combinatorial_mutation_data_long$mutation_count <- factor(
  combinatorial_mutation_data_long$mutation_count
)

fig_3b <- ggplot(
  combinatorial_mutation_data_long,
  aes(x = mutation_count, y = value, fill = mutation_count)
) +
  geom_violin() +
  geom_boxplot(width = 0.1,
               color = "black",
               outlier.shape = NA) +
  theme_bw() +
  scale_y_log10() +
  scale_x_discrete(labels = c("0" = "WT")) +
  labs(x = "Number of Mutated Residues", y = "Fluorescence", title = "Figure 3B. Replicate") +
  theme(legend.position = "none")


ggsave("figures/fig_3b.png", plot = fig_3b, width = 10, height = 6)  # Adjust width and height here
print(fig_3b)
```

### Generate Figure 3D

We first extract the data with more than one mutation since the single mutations (and the wild-type) by definition do not have any epistasis. 

```{R}
multiple_mutation_data <- filter(combinatorial_mutation_data, mutation_count > 1)
multiple_mutation_data$mutation_count <- factor(
    multiple_mutation_data$mutation_count
)

head(multiple_mutation_data[,c("mutants", "epistasis")])
```

We then use the multiple mutation data to generate the figure.

```{R}
fig_3d <- ggplot(multiple_mutation_data, 
    aes(x = mutation_count, y = epistasis)
) +
  geom_quasirandom(width = 0.4, size = 0.1, alpha = 0.5) +
  geom_boxplot(width = 0.1, color = "red", outliers = FALSE) +
  theme_bw() +
  ylim(-1.5, 0.5) +
  labs(x = "Number of Mutated Residues", y = "Fluorescence", title = "Figure 3D. Replicate") +
  theme(legend.position = "none")



ggsave("figures/fig_3d.png", plot = fig_3d, width = 10, height = 6)  # Adjust width and height here
print(fig_3d)
```
